import type { NextPage } from 'next';
import Head from 'next/head';
import AboutMe from './AboutMe';
import MinProjects from './MinProjects';
import RecentCompanies from './RecentCompanies';
import SocialConnection from './SocialConnection';
import Summary from './Summary/index';
import Contact from './Contact';
import Recommendations from './Recommendations';
import Projects from './Projects';
import Courses from './Courses';
import Volunteering from './Volunteering';
import Competitions from './Competitions';

export async function getStaticProps() {
  return {
    props: {}, // will be passed to the page component as props
  }
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Abdulhadi Jarad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SocialConnection />
    
      <div style={{ margin: '0px auto', maxWidth: 950}}>
        <Summary />
        <AboutMe />
        <Competitions/>
        <Volunteering/>
        <Courses/>
        <RecentCompanies />
        <Projects />
      </div>
      <div style={{ margin: '0px auto', maxWidth: 950 }}>
        <MinProjects />
        <Contact />
      </div>
        <Recommendations />
    </div>
  );
}

export default Home
